[features]
seeds = false
skip-lint = false
[programs.localnet]
cohesion = "8D1NPspyZ1fGY2FvuiBTXFCBLo3SKJY9QTdoyLqPbsTQ"

[programs.devnet]
cohesion = "8D1NPspyZ1fGY2FvuiBTXFCBLo3SKJY9QTdoyLqPbsTQ"

[programs.mainnet]
cohesion = "8D1NPspyZ1fGY2FvuiBTXFCBLo3SKJY9QTdoyLqPbsTQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/monarch/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
